### ISSUE TITLE
Generate new number after resetting random number guesser

### ISSUE THREAD

**Issue by bitbruder** [ManuelStaffa/website#1]
When resetting your random number game, a new number should be generated.

**Comment by ManuelStaffa** [comment]
It's not a bug. It's a feature.

**Comment by DanielRuf** [comment]
Was changed in https://github.com/ManuelStaffa/website/commit/50570b3d7a11be4b48bdcad3a3d53dca3058cc7a#diff-0364f57fbff2fabbe941ed20c328ef1aR119
